### ISSUE TITLE
dragBoundFunc and pos variable used on example

### ISSUE THREAD

**Issue by speedy32** [lavrton/KineticJS#1]
Hi 
Following example on JSDoc generate error when you will try to use pos variable.

node.dragBoundFunc(function(){
  return {
    x: this.getAbsolutePosition().x,
    y: pos.y
  };
});

It should be changed to:

node.dragBoundFunc(function(){
  return {
    x: this.getAbsolutePosition().x,
    y: this.getStage().getPointerPosition().y
  };
});

**Comment by lavrton** [comment]
thanks.
