### ISSUE TITLE
The differences between scene and hit ?

### ISSUE THREAD

**Issue by Jberryliu** [lavrton/KineticJS#10]
can you tell me the differences between scene region(renderer) and hit region(renderer) particularly? And why there will be a "hit" term? When should I use it?
Thanks.

**Comment by lavrton** [comment]
I think you will understand hit term in this example: http://lavrton.github.io/KineticJS/Events/Custom_Hit_Region.html

In short: `scene` define how shape looks. `hit` define area of event reaction.

One of the most useful case: you have a very thin line on canvas. You need to listen click event on it. But it is not easy to click on such line. So you can increase hit area of the line.
