### ISSUE TITLE
.find() works differently to previous version?

### ISSUE THREAD

**Issue by bensquire** [lavrton/KineticJS#3]
Hi @lavrton thanks for forking this, hopefully KineticJS will continue to see the love it deserves.

On 5.1.0 This code worked flawlessly previously:

        var boundingBox = group.find('.bounding-box');
	if (boundingBox.length == 0) {
		throw 'Unable to set drag bounds. Could not find bounding box element';
	}

and by that I mean the length wasn't typically 0. However 5.1.9 broke this and now it always equates to 0. Did I miss something?

**Comment by lavrton** [comment]
Right. Looks like bug. But still not working for previous version (5.1.0) : http://jsbin.com/foqule/1/edit?html,js,console,output

Works fine without "-" char (if name will `boundingbox`)

**Comment by lavrton** [comment]
Bad test. You are right. It was working.

**Comment by bensquire** [comment]
@lavrton Awesome thanks for the fast turn around on this. I'll give it a go shortly :)

**Comment by bensquire** [comment]
Works a treat, thanks!

**Comment by bensquire** [comment]
@lavrton Can we get this bug fix pulled into a tagged release please? (5.2.0?)

**Comment by lavrton** [comment]
I will tag new version soon. But I want to implement some more features before.
