### ISSUE TITLE
Line() misbehaves when given an X or Y

### ISSUE THREAD

**Issue by dark12222000** [lavrton/KineticJS#8]
Reproduce:

Create a line with an X and Y set, and feed it the same X and Y as it's first set of points:

```javascript
Kinetic.Line({
  x: 25,
  y: 25,
  stroke: 'red',
  points: [25, 25, 100, 100]
});
```

The line doesn't actually appear where it should.. instead it seems to appear at 50, 50. Obviously this effect is worse the farther from 0,0 you start the line.  We probably shouldn't be able to give lines an X or a Y at all.

**Comment by lavrton** [comment]
50, 50 - is expected line position. Points are relative to `{x,y}` position.

Every `Kinetic.Node` must have x, y position. While dragging a line we will change just `{x, y}` (not whole `points` array).

**Comment by dark12222000** [comment]
Makes sense. Can we update docs to reflect this and make it more clear?
